LoginRegister/Controllers/ProductController.cs
using Entity.Business.Abstract;
using Entity.Domain.Entity;
using Entity.Utilities.Constant;
using Oblivion.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace Oblivion.Controllers
{
    
    public class ProductController : Controller
    {
        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int category)
        {
            var model = new ProductModel
            {
                Products = category > 0 ? _productService.GetListByCategory(category).Data : _productService.GetList().Data

            };
            return View(model);
        }

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public IActionResult GetProducts(int category)
        {
            //ViewBag.Message = "Hello"; //TempData["Message"];
            //ViewData["Message"] = "Welcome Oblivion";


            //var customers = new List<Product>();
            //var product = new List<ProductModel>();

            //foreach (var item in customers)
            //{
            //    var model = new ProductModel
            //    {
            //      ProductId=item.ProductId,
            //      ProductName=item.ProductName

            //    };

            //    product.Add(model);
            //}
           
            var model = new ProductModel
            {
                Products = category > 0 ? _productService.GetListByCategory(category).Data : _productService.GetList().Data

            };
            
            return View(model);
            

            //return View(product);
        }

        //[HttpGet]
        //public IActionResult GetProducts(int id)
        //{
        //    var customer = _productService.GetById(id);

        //    return View();
        //}


        [HttpGet]
        public IActionResult Add()
        {
            return View(new ProductModel());
        }
        [HttpPost]
        public IActionResult Add(ProductModel product)
        {
            if (ModelState.IsValid)
            {
                var user = new Product
                {
                     
                    ProductName = product.ProductName,
                    CategoryId = product.CategoryId,
                    Description = product.Description,
                    UnitPrice = product.UnitPrice,
                    UnitsInStock = product.UnitsInStock
                };
                _productService.Add(user);
                TempData["message"] = Messages.ProductAdded;
                return RedirectToAction("GetProducts");
            }
            else
            {
                return View(product);
            }
        }


     
        [HttpGet]
        public IActionResult Delete(int productId)
        {
            var products = _productService.GetById(productId);
            _productService.Delete(products.Data);
            TempData["message"] = Messages.ProductDeleted;
            return RedirectToAction("GetProducts");
        }
        [HttpGet]
        public IActionResult Update(int productId)
        {
            ViewData["message"] = Messages.UpdateView;
            var products = _productService.GetById(productId).Data;

            var user = new ProductModel
            {
                
                ProductName = products.ProductName,
                CategoryId = products.CategoryId,
                Description = products.Description,
                UnitPrice = products.UnitPrice,
                UnitsInStock = products.UnitsInStock

            };
            //var users = _productService.Update(user);
            return View("Update", user);
        }
        [HttpPost]
        public IActionResult Update(ProductModel productModel)
        {
            if (ModelState.IsValid)
            {
                var product = _productService.GetById(productModel.ProductId).Data;

                product.ProductName = productModel.ProductName;
                product.CategoryId = productModel.CategoryId;
                product.Description = productModel.Description;
                product.UnitPrice = productModel.UnitPrice;
                product.UnitsInStock = productModel.UnitsInStock;
                _productService.Update(product);
                TempData["Message"] = Messages.ProductUpdated;
                return RedirectToAction("GetProducts");

            }
            else
            {
                return View("Update", productModel);
            }     
        }
         
        public IActionResult Search(string productName)
        {
            Product product = new Product();

            return View();
        }
    }
}

LoginRegister/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Oblivion.Models;
using Oblivion.Models.Account;
using Oblivion.Models.Account.Roles;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Oblivion.Controllers
{
    #region Old Role Edit
    //public async Task<IActionResult> RoleAssign(string userId)
    //{
    //    var user = await _userManager.FindByIdAsync(userId);
    //    //string id = "f192b27f-a894-4bd6-9dcb-8101eac63b46";
    //    //var user = await _userManager.FindByIdAsync(id);
    //    var identityRoles = _roleManager.Roles.ToList();
    //    List<string> userRoles = await _userManager.GetRolesAsync(user) as List<string>;
    //    List<RoleAssignViewModel> roleAssignViewModels = new List<RoleAssignViewModel>();
    //    identityRoles.ForEach(role => roleAssignViewModels.Add(new RoleAssignViewModel
    //    {
    //        HasAssign = userRoles.Contains(role.Name),
    //        Id = role.Id,
    //        RoleName = role.Name
    //    }));
    //    return View(roleAssignViewModels);
    //}

    //[HttpPost]
    //public async Task<IActionResult> RoleAssign(List<RoleAssignViewModel> modelList)
    //{
    //    string id = "f192b27f-a894-4bd6-9dcb-8101eac63b46";
    //    var user = await _userManager.FindByIdAsync(id);
    //    foreach (RoleAssignViewModel role in modelList)
    //    {
    //        if (role.HasAssign)
    //            await _userManager.AddToRoleAsync(user, role.RoleName);
    //        else
    //            await _userManager.RemoveFromRoleAsync(user, role.RoleName);
    //    }
    //    return RedirectToAction("Index", "Account");
    //}
    #endregion
    #region Update
    //if (id != null)
    //{
    //    IdentityRole role = await _roleManager.FindByIdAsync(id);
    //    role.Name = roleViewModel.RoleName;
    //    await _roleManager.UpdateAsync(role);
    //}
    //else
    //{
    //    var newRole = await _roleManager.CreateAsync(new IdentityRole { Name = roleViewModel.RoleName });
    //    if (newRole.Succeeded)
    //    {
    //        RedirectToAction("Index", "Role");
    //    }
    //}
    //return View();
    #endregion
    [HtmlTargetElement("td", Attributes = "i-role")]
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;


        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
      
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(string name)
        {
            if (ModelState.IsValid)
            {

                var newRole = await _roleManager.CreateAsync(new IdentityRole(name));
                if (newRole.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var item in newRole.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }

            }
            return View(name);
        }

        public async Task<IActionResult> UpdateRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<User> members = new List<User>();
            List<User> nonMembers = new List<User>();
            foreach (var user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            RoleEdit rw = new RoleEdit()
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            };
            return View(rw);

         
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRole(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    User user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)

                            foreach (var item in result.Errors)

                                ModelState.AddModelError(item.Code, item.Description);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    User user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            foreach (var item in result.Errors)
                                ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }
            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await UpdateRole(model.RoleId);
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }
            return View("Index", _roleManager.Roles);
        }




        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }
    }
}

LoginRegister/Controllers/UserController.cs
using Email;
using Entity.Utilities.Constant;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Oblivion.Models;
using Oblivion.Models.Account;
using System.Threading.Tasks;
using System.Linq;
using Entity.Business.Abstract;
using System.Security.Claims;

namespace Oblivion.Controllers
{

    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IUserValidator<User> _userValidator;
        private readonly IPasswordValidator<User> _passwordValidator;
        private readonly IPasswordHasher<User> _passwordHasher;
        private readonly IEmailSender _emailSender;
        private readonly IProductService _productService;
        private readonly SignInManager<User> _signInManager;
        public UserController(UserManager<User> usrMgr, IPasswordHasher<User> passwordHash, 
            IPasswordValidator<User> passwordVal, IProductService productService,
            IUserValidator<User> userValid, IEmailSender emailSender,
            SignInManager<User> signInManager) 
        {
            _userManager = usrMgr;
            _passwordHasher = passwordHash;
            _passwordValidator = passwordVal;
            _userValidator = userValid;
            _emailSender = emailSender;
            _productService = productService;
            _signInManager = signInManager;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_userManager.Users);
            
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user.UserName == "oblivion33")
            {
                TempData["message"] = Messages.TriedDeleteAdmin;
                RedirectToAction(nameof(Index));
            }
            //else if (_userManager.Users==null)
            //{
            //    await _signInManager.SignOutAsync();
            //}
            else
            {
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(error.Code, error.Description);
                }
            }
            return View("Index", _userManager.Users);
        }
        [AllowAnonymous]
        public async Task<IActionResult> UpdateUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            else
                return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> UpdateUser(string id, string email, string password)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult validEmail = null;
                if (!string.IsNullOrEmpty(email))
                {
                    validEmail = await _userValidator.ValidateAsync(_userManager, user);
                    if (validEmail.Succeeded)
                        user.Email = email;
                    else
                        Errors(validEmail);
                }
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                IdentityResult validPass = null;
                if (!string.IsNullOrEmpty(password))
                {
                    validPass = await _passwordValidator.ValidateAsync(_userManager, user, password);
                    if (validPass.Succeeded)
                        user.PasswordHash = _passwordHasher.HashPassword(user, password);
                    else
                        Errors(validPass);
                }
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (validEmail != null && validPass != null && validEmail.Succeeded && validPass.Succeeded)
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    ;
                    var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var confirmationLink = Url.Action("ConfirmEmail",
                 "Account", new { token, email = user.Email }, Request.Scheme);

                    var message = new Message(new string[] { user.Email }, "Confirmation email link", confirmationLink, null);
                  
                    await _emailSender.SendEmailAsync(message);
                    if (User.Identity.Name=="oblivion33")
                    {
                        if (result.Succeeded)
                            return RedirectToAction("Index");
                        else
                            Errors(result);
                    }
                    else
                    {
                        if (result.Succeeded)
                            return RedirectToAction("EditProfile");
                        else
                            Errors(result);
                    }
                   
                }

            }
            else
                ModelState.AddModelError("", "User Not Found");

            return View(user);

        }
        [AllowAnonymous]
        public async Task<IActionResult> EditProfile()
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
           
             
            return View(user);
        }


        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);



    }
}

LoginRegister/Views/Product/Add.cshtml
@model ProductModel
@* ctrl+e ctrl+d *@

@{
    string action = (Model?.ProductId ?? 0) > 0 ? "Update" : "Add";
}

<div class="alert-primary">@ViewBag.Message</div>


<form class="form-group" asp-action="@action" asp-controller="Product">

    <input asp-for="ProductId" hidden />

    <div class="form-group">
        <label for="name" class="mr-sm-2">ProductName:</label>
        <input asp-for="ProductName" class="form-control mb-2 mr-sm-2" id="name">
        <span asp-validation-for="ProductName"></span>
    </div>

    <div class="form-group">
        <label for="desc" class="mr-sm-2">CategoryId</label>
        <input asp-for="CategoryId" type="number" class="form-control mb-2 mr-sm-2" id="desc" />
        <span asp-validation-for="CategoryId"></span>
    </div>

    <div class="form-group">
        <label for="name" class="mr-sm-2">Description:</label>
        <input asp-for="Description" class="form-control mb-2 mr-sm-2" id="name" />
        <span asp-validation-for="Description"></span>
    </div>
    <div class="form-group">
        <label for="desc" class="mr-sm-2">UnitPrice:</label>
        <input asp-for="UnitPrice" type="number" class="form-control mb-2 mr-sm-2" id="desc" />
        <span asp-validation-for="UnitPrice"></span>
    </div>
    <div class="form-group">
        <label for="desc" class="mr-sm-2">UnitsInStock:</label>
        <input asp-for="UnitsInStock" type="number" class="form-control mb-2 mr-sm-2" id="desc" />
        <span asp-validation-for="UnitsInStock"></span>
    </div>


    <button type="submit" class="btn btn-primary bgupdate">@action</button>




</form>
<partial name="_ValidationScriptsPartial" />

LoginRegister/Views/Product/GetProducts.cshtml
@model ProductModel
@*<div style="color:darkblue" >@ViewBag.Message</div>*@
@*<div>@ViewData["Message"]</div>*@ @*Bu iksi eyni kodu icra edir ve eyni seyi yazir netice olaraq*@
@{
    Layout = "_Layout";
}


<div class="">@ViewBag.Message</div>

<div class="container mb-1 mt-1" style="margin:10px;overflow-x:auto;">

    <h1 class="alert-heading" style="color:white">Products</h1>

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>CategoryId</th>
                <th>Description</th>
                <th>UnitPrice</th>
                <th>UnitsInStock</th>
                <th>
                    <a class="btn btn-success bgprice" asp-action="Add" asp-controller="Product">Create Product</a>
                </th>

            </tr>
        </thead>

        <tbody>
            @*@{
                    int i = 1;
                }*@

            @foreach (var item in Model.Products)
            {
                <tr>
                    <td>@item.ProductId</td>
                    <td>@item.ProductName</td>
                    <td>@item.CategoryId</td>
                    <td>@item.Description</td>
                    <td>@item.UnitPrice</td>
                    <td>@item.UnitsInStock</td>
                    <td>
                        <a class="btn btn-success bgprice" asp-route-productId="@item.ProductId" asp-action="Update" asp-controller="Product">Update</a>
                    </td>
                    <td>
                        <a class="btn btn-danger bgprice" asp-route-productId="@item.ProductId" asp-action="Delete" asp-controller="Product">Delete</a>
                    </td>
                </tr>

                //i++;
            }
        </tbody>


        <tfoot>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>CategoryId</th>
                <th>Description</th>
                <th>UnitPrice</th>
                <th>UnitsInStock</th>
            </tr>
        </tfoot>
    </table>


</div>

<partial name="_ValidationScriptsPartial" />

LoginRegister/Views/Product/Update.cshtml
@model ProductModel
@* ctrl+e ctrl+d *@




    <div class="alert-primary" style="">@ViewBag.Message</div>
    @*<div>@ViewData["MyMessage"]</div>*@

    <form class="form-group" asp-action="Update" asp-controller="Product">

        <input asp-for="ProductId" hidden />

        <div class="form-group">
            <label for="name" class="mr-sm-2">ProductName:</label>
            <input asp-for="ProductName" class="form-control mb-2 mr-sm-2" id="name">
            <span asp-validation-for="ProductName"></span>
        </div>

        <div class="form-group">
            <label for="desc" class="mr-sm-2">CategoryId:</label>
            <input asp-for="CategoryId" type="number" class="form-control mb-2 mr-sm-2" id="desc" />
            <span asp-validation-for="CategoryId"></span>
        </div>


        <div class="form-group">
            <label for="name" class="mr-sm-2">Description:</label>
            <input asp-for="Description" class="form-control mb-2 mr-sm-2" id="name" />
            <span asp-validation-for="Description"></span>
        </div>


        <div class="form-group">
            <label for="desc" class="mr-sm-2">UnitPrice:</label>
            <input asp-for="UnitPrice" type="number" class="form-control mb-2 mr-sm-2" id="desc" />
            <span asp-validation-for="UnitPrice"></span>
        </div>
        <div class="form-group">
            <label for="desc" class="mr-sm-2">UnitsInStock:</label>
            <input asp-for="UnitsInStock" type="number" class="form-control mb-2 mr-sm-2" id="desc" />
            <span asp-validation-for="UnitsInStock"></span>
        </div>


        <button type="submit" class="btn btn-primary bgupdate">Update</button>
    </form>
   


<partial name="_ValidationScriptsPartial" />

LoginRegister/Views/Product/gtProductLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OBLIVION</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @*<link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/bootstrap.css" />*@
</head>

<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-expand-lg bg-white border-bottom box-shadow mb-3">*@
        <nav class="navbar navbar-expand-lg bg-dark ">
            <div class="container">

                <a style="color:white" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OBLIVION</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">*@
            <div class="collapse navbar-collapse justify-content-end">

                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.Identity.Name == "oblivion33")
                    {

                        <ul class="navbar-nav ">
                            @*flex-grow-1*@
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Product" asp-action="Index">PRODUCT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">SHOW CART</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Order" asp-action="Ship">ORDERS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Product" asp-action="GetProducts">CRUD PRODUCT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="User" asp-action="Index">USERS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Role" asp-action="Index">ROLES</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">CONTACT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Account" asp-action="Logout">LOGOUT</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav ">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">HOME</a>
                            </li>
                            <li>
                                <a class="nav-link text-white" asp-controller="Product" asp-action="Index">PRODUCT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">SHOW CART</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">CONTACT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="User" asp-action="EditProfile">EDIT PROFILE</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Account" asp-action="Logout">LOGOUT</a>
                            </li>
                        </ul>
                    }

                }
                else
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">HOME</a>
                        </li>
                        <li>
                            <a class="nav-link text-white" asp-controller="Product" asp-action="Index">PRODUCT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">CONTACT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">SHOW CART</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Account" asp-action="Login">LOG IN</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Account" asp-action="Register">REGISTER</a>
                        </li>
                    </ul>
                }



            </div>
            </div>

        </nav>
    </header>
    <br />

    @{ 
        
    }
    <section @*style="background: url(https://www.sprim.com/wp-content/uploads/2018/12/Digital-AI-Tools-Hero.jpg) center center no-repeat;background-size: auto"*@>
        <div class="container">
            <main role="main" class="pb-3">
                <div class="row">
                    @if (TempData["message"] != null)
                    {
                        <div class="alert alert-primary">@TempData["message"]</div>
                    }
                </div>

                
               
                <div class="row">
                    <div class="col-4">
                        @await Component.InvokeAsync("CategoryList")
                    </div>
                    <div class="col-8">@RenderBody()</div>
                </div>

            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Oblivion - <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </section>

</body>
</html>