LoginRegister/Controllers/OrderController.cs
using Entity.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Oblivion.Models;

namespace Oblivion.Controllers
{
    
    public class OrderController : Controller
    {
        private readonly IOrderService _shippingService;
        private readonly IOrderDetailService _orderDetailService;
        public OrderController(IOrderService shippingService,IOrderDetailService orderDetailService)
        {
            _shippingService = shippingService;
            _orderDetailService = orderDetailService;
        }
        public IActionResult Ship()
        {
            var model = new OrderModel
            {
                Orders = _shippingService.GetAll()
            };
            return View(model);
        }
        public IActionResult OrderDetail()
        {
            var model = new OrderDetailModel
            {
                orderDetail = _orderDetailService.GetAll()
            };
            return View(model);
        }
    }
}

LoginRegister/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.TagHelpers;
using Oblivion.Models;
using Oblivion.Models.Account;
using Oblivion.Models.Account.Roles;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Oblivion.Controllers
{
    #region Old Role Edit
    //public async Task<IActionResult> RoleAssign(string userId)
    //{
    //    var user = await _userManager.FindByIdAsync(userId);
    //    //string id = "f192b27f-a894-4bd6-9dcb-8101eac63b46";
    //    //var user = await _userManager.FindByIdAsync(id);
    //    var identityRoles = _roleManager.Roles.ToList();
    //    List<string> userRoles = await _userManager.GetRolesAsync(user) as List<string>;
    //    List<RoleAssignViewModel> roleAssignViewModels = new List<RoleAssignViewModel>();
    //    identityRoles.ForEach(role => roleAssignViewModels.Add(new RoleAssignViewModel
    //    {
    //        HasAssign = userRoles.Contains(role.Name),
    //        Id = role.Id,
    //        RoleName = role.Name
    //    }));
    //    return View(roleAssignViewModels);
    //}

    //[HttpPost]
    //public async Task<IActionResult> RoleAssign(List<RoleAssignViewModel> modelList)
    //{
    //    string id = "f192b27f-a894-4bd6-9dcb-8101eac63b46";
    //    var user = await _userManager.FindByIdAsync(id);
    //    foreach (RoleAssignViewModel role in modelList)
    //    {
    //        if (role.HasAssign)
    //            await _userManager.AddToRoleAsync(user, role.RoleName);
    //        else
    //            await _userManager.RemoveFromRoleAsync(user, role.RoleName);
    //    }
    //    return RedirectToAction("Index", "Account");
    //}
    #endregion
    #region Update
    //if (id != null)
    //{
    //    IdentityRole role = await _roleManager.FindByIdAsync(id);
    //    role.Name = roleViewModel.RoleName;
    //    await _roleManager.UpdateAsync(role);
    //}
    //else
    //{
    //    var newRole = await _roleManager.CreateAsync(new IdentityRole { Name = roleViewModel.RoleName });
    //    if (newRole.Succeeded)
    //    {
    //        RedirectToAction("Index", "Role");
    //    }
    //}
    //return View();
    #endregion
    [HtmlTargetElement("td", Attributes = "i-role")]
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<User> _userManager;


        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
      
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(string name)
        {
            if (ModelState.IsValid)
            {

                var newRole = await _roleManager.CreateAsync(new IdentityRole(name));
                if (newRole.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                foreach (var item in newRole.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }

            }
            return View(name);
        }

        public async Task<IActionResult> UpdateRole(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<User> members = new List<User>();
            List<User> nonMembers = new List<User>();
            foreach (var user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            RoleEdit rw = new RoleEdit()
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            };
            return View(rw);

         
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRole(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    User user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)

                            foreach (var item in result.Errors)

                                ModelState.AddModelError(item.Code, item.Description);
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    User user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            foreach (var item in result.Errors)
                                ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }
            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await UpdateRole(model.RoleId);
        }

        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(item.Code, item.Description);
                    }
                }
            }
            return View("Index", _roleManager.Roles);
        }




        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }
    }
}

LoginRegister/Controllers/UserController.cs
using Email;
using Entity.Utilities.Constant;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Oblivion.Models;
using Oblivion.Models.Account;
using System.Threading.Tasks;
using System.Linq;
using Entity.Business.Abstract;
using System.Security.Claims;

namespace Oblivion.Controllers
{

    public class UserController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IUserValidator<User> _userValidator;
        private readonly IPasswordValidator<User> _passwordValidator;
        private readonly IPasswordHasher<User> _passwordHasher;
        private readonly IEmailSender _emailSender;
        private readonly IProductService _productService;
        private readonly SignInManager<User> _signInManager;
        public UserController(UserManager<User> usrMgr, IPasswordHasher<User> passwordHash, 
            IPasswordValidator<User> passwordVal, IProductService productService,
            IUserValidator<User> userValid, IEmailSender emailSender,
            SignInManager<User> signInManager) 
        {
            _userManager = usrMgr;
            _passwordHasher = passwordHash;
            _passwordValidator = passwordVal;
            _userValidator = userValid;
            _emailSender = emailSender;
            _productService = productService;
            _signInManager = signInManager;
        }
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(_userManager.Users);
            
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user.UserName == "oblivion33")
            {
                TempData["message"] = Messages.TriedDeleteAdmin;
                RedirectToAction(nameof(Index));
            }
            //else if (_userManager.Users==null)
            //{
            //    await _signInManager.SignOutAsync();
            //}
            else
            {
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var error in result.Errors)
                        ModelState.AddModelError(error.Code, error.Description);
                }
            }
            return View("Index", _userManager.Users);
        }
        [AllowAnonymous]
        public async Task<IActionResult> UpdateUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
                return View(user);
            else
                return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> UpdateUser(string id, string email, string password)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult validEmail = null;
                if (!string.IsNullOrEmpty(email))
                {
                    validEmail = await _userValidator.ValidateAsync(_userManager, user);
                    if (validEmail.Succeeded)
                        user.Email = email;
                    else
                        Errors(validEmail);
                }
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                IdentityResult validPass = null;
                if (!string.IsNullOrEmpty(password))
                {
                    validPass = await _passwordValidator.ValidateAsync(_userManager, user, password);
                    if (validPass.Succeeded)
                        user.PasswordHash = _passwordHasher.HashPassword(user, password);
                    else
                        Errors(validPass);
                }
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (validEmail != null && validPass != null && validEmail.Succeeded && validPass.Succeeded)
                {
                    IdentityResult result = await _userManager.UpdateAsync(user);
                    ;
                    var token = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var confirmationLink = Url.Action("ConfirmEmail",
                 "Account", new { token, email = user.Email }, Request.Scheme);

                    var message = new Message(new string[] { user.Email }, "Confirmation email link", confirmationLink, null);
                  
                    await _emailSender.SendEmailAsync(message);
                    if (User.Identity.Name=="oblivion33")
                    {
                        if (result.Succeeded)
                            return RedirectToAction("Index");
                        else
                            Errors(result);
                    }
                    else
                    {
                        if (result.Succeeded)
                            return RedirectToAction("EditProfile");
                        else
                            Errors(result);
                    }
                   
                }

            }
            else
                ModelState.AddModelError("", "User Not Found");

            return View(user);

        }
        [AllowAnonymous]
        public async Task<IActionResult> EditProfile()
        {

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
           
             
            return View(user);
        }


        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }
        private Task<User> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);



    }
}

LoginRegister/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OBLIVION</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/Search.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



    @*<link rel="stylesheet" href="~/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/bootstrap.css" />*@
</head>

<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-expand-lg bg-white border-bottom box-shadow mb-3">*@
        <nav class="navbar navbar-expand-lg bg-dark ">
            <div class="container">

                <a style="color:white" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OBLIVION</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @*<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">*@
                <div class="collapse navbar-collapse justify-content-end">
                   
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.Identity.Name == "leman03")
                        {

                            <ul class="navbar-nav ">
                                @*flex-grow-1*@
                               

                                <li class="nav-item">
                                    <form class="example" action="action_page.php">
                                        <input type="text" placeholder="Search.." name="search">
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </form>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">HOME</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Product" asp-action="Index">PRODUCT</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">SHOW CART</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Order" asp-action="Ship">ORDERS</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Product" asp-action="GetProducts">CRUD PRODUCT</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="User" asp-action="Index">USERS</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Role" asp-action="Index">ROLES</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">CONTACT</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Account" asp-action="Logout">LOGOUT</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav ">
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">HOME</a>
                                </li>
                                <li>
                                    <a class="nav-link text-white" asp-controller="Product" asp-action="Index">PRODUCT</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">SHOW CART</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">CONTACT</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="User" asp-action="EditProfile">EDIT PROFILE</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Account" asp-action="Logout">LOGOUT</a>
                                </li>
                            </ul>
                        }

                    }
                    else
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Privacy">HOME</a>
                            </li>
                            <li>
                                <a class="nav-link text-white" asp-controller="Product" asp-action="Index">PRODUCT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Home" asp-action="Contact">CONTACT</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Cart" asp-action="Index">SHOW CART</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Account" asp-action="Login">LOG IN</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Account" asp-action="Register">REGISTER</a>
                            </li>
                        </ul>
                    }


                </div>
            </div>


        </nav>
    </header>


    <section style="background: url()    no-repeat;background-size:100%">
        <div class="container">
            <main role="main" class="pb-3">
                <div class="row">
                    @if (TempData["message"] != null)
                    {
                        <div class="alert alert-primary">@TempData["message"]</div>
                    }
                </div>



                <div class="row">

                    <div class="col-12">@RenderBody()</div>
                </div>

            </main>
        </div>
    </section>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Oblivion - <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
         
        </div>
     
          
        
       
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>